- name: Criando o Security Group
  local_action:
   module: ec2_group
   name: "{{ security_group }}"
   description: Security Group Desafio02
   region: "{{ region }}"
   rules:
   - proto: tcp
     from_port: 22
     to_port: 22
     cidr_ip: 0.0.0.0/0
   - proto: tcp
     from_port: 80
     to_port: 80
     cidr_ip: 0.0.0.0/0
   - proto: tcp
     from_port: 53
     to_port: 53
     cidr_ip: 0.0.0.0/0
   - proto: tcp
     from_port: 8080
     to_port: 8080
     cidr_ip: 0.0.0.0/0
   - proto: udp
     from_port: 8080
     to_port: 8080
     cidr_ip: 0.0.0.0/0
   - proto: tcp
     from_port: 443
     to_port: 443
     cidr_ip: 0.0.0.0/0
   - proto: udp
     from_port: 443
     to_port: 443
     cidr_ip: 0.0.0.0/0
   - proto: tcp
     from_port: 53
     to_port: 53
     cidr_ip: 0.0.0.0/0
#   - proto: icmp
#     from_port: all
#     to_port: all
#     cidr_ip: 0.0.0.0/0
#   rules_egress:
#   - proto: all
#     cidr_ip: 0.0.0.0/0
  register: basic_firewall


- name: Criando a instancia EC2
  local_action: ec2
   group={{ security_group }}
   instance_type={{ instance_type }}
   image={{ image }}
   wait=true
   region={{ region }}
   keypair={{ keypair }}
   count={{ count }}
  register: ec2

- name: Obtendo IP Público
  ipify_facts:
  register: public_ip

- name: Adicionando a instancia criada no arquivo hosts
  local_action: lineinfile
   dest="./hosts"
   regexp={{ item.public_ip }}
   insertafter="[desafio02]" line={{ item.public_ip }}
  with_items: "{{ ec2.instances }}"

- name: Esperando o SSH
  local_action: wait_for
   host={{ item.public_ip }}
   port=22
   state=started
  with_items: "{{ ec2.instances }}"

- name: Adicionando o Nome tag na instancia
  local_action: ec2_tag resource={{ item.id }} region={{ region }} state=present 
  with_items: "{{ ec2.instances }}"
  args:
   tags: 
    Name: desafio02-lohan
    Env: pulmao
  
- name: Criando Zona de DNS
  route53_zone:
    zone: "{{ domain }}"
    comment: challenge domain
    state: present



#- name: Criando entrada DNS .
#  route53:
#         state: present
#         zone: "{{ domain }}"
#         record: 
#         type: A
#         ttl: "{{ ttl }}"
#         value: "{{ public_ip.ansible_facts.ipify_public_ip }}"
#         wait: yes

- name: Criando entrada DNS blog         
  route53:
         state: present
         zone: "{{ domain }}"
         record: blog.desafio02lohan.tk
         type: CNAME
         ttl: "{{ ttl }}"
         value: "{{ domain }}"
         wait: yes
- name: Criando entrada DNS tomcat
  route53:
         state: present
         zone: "{{ domain }}"
         record: tomcat.desafio02lohan.tk
         type: CNAME
         ttl: "{{ ttl }}"
         value: "{{ domain }}"
         wait: yes
- name: Criando entradas DNS loja-blog
  route53:
         state: present
         zone: "{{ domain }}"
         record: loja-blog.desafio02lohan.tk
         type: CNAME
         ttl: "{{ ttl }}"
         value: "{{ domain }}"
         wait: yes
- name: Criando entrada DNS site
  route53:
         state: present
         zone: "{{ domain }}"
         record: site.desafio02lohan.tk
         type: CNAME
         ttl: "{{ ttl }}"
         value: "{{ domain }}"
         wait: yes
- name: Criando entrada DNS www
  route53:
         state: present
         zone: "{{ domain }}"
         record: www.desafio02lohan.tk
         type: CNAME
         ttl: "{{ ttl }}"
         value: "{{ domain }}"
         wait: yes
 

